# Generated by Django 4.2.23 on 2026-09-26 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_merge_0023_sessions_and_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSurfaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('surface_key', models.CharField(db_index=True, max_length=128)),
                ('module_key', models.CharField(db_index=True, max_length=64)),
                ('is_visible', models.BooleanField(default=True)),
                ('label_override', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surface_configs', to='core.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'surface_key')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('module_key', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('label_override', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_configs', to='core.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'module_key')},
            },
        ),
    ]
