-- Decision service schema ownership draft.
-- This migration mirrors the tables the .NET service reads/writes today.
-- It is intentionally idempotent so it can be introduced without dropping the
-- existing Django-created tables.

CREATE TABLE IF NOT EXISTS decisions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    title varchar(255),
    context_summary text,
    reasoning text,
    risk_level varchar(20),
    confidence integer,
    status varchar(32) NOT NULL,
    requires_approval boolean NOT NULL DEFAULT false,
    planned_decision_date timestamptz,
    committed_at timestamptz,
    approved_at timestamptz,
    is_reference_case boolean NOT NULL DEFAULT false,
    created_by_agent boolean NOT NULL DEFAULT false,
    agent_session_id uuid,
    is_pre_draft boolean NOT NULL DEFAULT false,
    project_id integer REFERENCES core_project(id) DEFERRABLE INITIALLY DEFERRED,
    project_seq integer NOT NULL DEFAULT 1,
    author_id integer REFERENCES core_customuser(id) DEFERRABLE INITIALLY DEFERRED,
    last_edited_by_id integer REFERENCES core_customuser(id) DEFERRABLE INITIALLY DEFERRED,
    committed_by_id integer REFERENCES core_customuser(id) DEFERRABLE INITIALLY DEFERRED,
    approved_by_id integer REFERENCES core_customuser(id) DEFERRABLE INITIALLY DEFERRED,
    topic varchar(80) NOT NULL DEFAULT 'general',
    slug varchar(255) UNIQUE
);

CREATE INDEX IF NOT EXISTS decisions_project_status_idx
    ON decisions(project_id, status)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS decision_options (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    decision_id integer NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
    text text NOT NULL,
    is_selected boolean NOT NULL DEFAULT false,
    "order" integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS decision_options_decision_idx
    ON decision_options(decision_id, "order")
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS decision_signals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    decision_id integer NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
    created_by_id integer REFERENCES core_customuser(id) DEFERRABLE INITIALLY DEFERRED,
    metric varchar(120),
    movement varchar(80),
    period varchar(120),
    comparison varchar(120) NOT NULL DEFAULT 'vs_previous_period',
    scope_type varchar(80),
    scope_value varchar(255),
    delta_value numeric,
    delta_unit varchar(80),
    display_text_override text
);

CREATE INDEX IF NOT EXISTS decision_signals_decision_idx
    ON decision_signals(decision_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS decision_edges (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    from_decision_id integer NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
    to_decision_id integer NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
    created_by_id integer REFERENCES core_customuser(id) DEFERRABLE INITIALLY DEFERRED,
    edge_type varchar(40) NOT NULL DEFAULT 'related',
    CONSTRAINT decision_edges_no_self_link CHECK (from_decision_id <> to_decision_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS decision_edges_unique_active_idx
    ON decision_edges(from_decision_id, to_decision_id, edge_type)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS decision_reviews (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    decision_id integer NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
    reviewer_id integer REFERENCES core_customuser(id) DEFERRABLE INITIALLY DEFERRED,
    outcome_text text NOT NULL,
    reflection_text text NOT NULL,
    decision_quality varchar(80) NOT NULL,
    reviewed_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS decision_reviews_decision_idx
    ON decision_reviews(decision_id)
    WHERE is_deleted = false;
