# Generated by Django 4.2.30 on 2026-09-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0002_backfill_encrypt_tokens'),
        ('campaign', '0005_campaigntemplate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPlatformIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync_error', models.CharField(blank=True, choices=[('', 'No error'), ('auth', 'Reconnect required'), ('transient', 'Temporary failure'), ('unknown', 'Sync failed')], default='', max_length=16)),
                ('last_sync_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_integration.metaadaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_integrations', to='campaign.campaign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='campaignplatformintegration',
            constraint=models.UniqueConstraint(fields=('campaign', 'ad_account'), name='campaign_platform_account_unique'),
        ),
    ]
