# Generated by Django 4.2.30 on 2026-10-07 05:39

from django.db import migrations, models
import django.db.models.deletion


def backfill_organization(apps, schema_editor):
    """
    Attribute existing customers to their workspace through their customer
    organisation, which records it unambiguously. project_id is not used: project
    ids repeat across organisation schemas, so guessing from it could pin a
    customer to the wrong workspace. Customers without an organisation stay NULL.
    """
    Customer = apps.get_model('customer', 'Customer')
    CustomerOrganisation = apps.get_model('customer', 'CustomerOrganisation')
    for organisation in CustomerOrganisation.objects.exclude(organization_id=None).only('id', 'organization_id'):
        Customer.objects.filter(organisation_id=organisation.id).update(
            organization_id=organisation.organization_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_0023_sessions_and_ai'),
        ('customer', '0012_status_label_project_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csm_customers', to='core.organization'),
        ),
        migrations.RunPython(backfill_organization, migrations.RunPython.noop),
    ]
