# Generated by Django 4.2.30 on 2026-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_copy_variation', '0004_adcopyvariation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcopyvariation',
            name='model_name',
            field=models.CharField(default='qwen3:4b', max_length=64),
        ),
    ]
