# Generated by Django 4.2.30 on 2026-09-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_copy_variation', '0004_adcopyvariation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcopyvariation',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
