
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from django.core.exceptions import ImproperlyConfigured
from celery.schedules import crontab



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-4g=$b1l14w5*aia@bgix6zv9%ky2#elk0f*jso867wpgcq8&3u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    h.strip() for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'django_fsm',
    'channels',
    'audit.apps.AuditConfig',
    'authentication.apps.AuthenticationConfig',
    'core.apps.CoreConfig',
    'spreadsheet.apps.SpreadsheetConfig',
    'access_control.apps.AccessControlConfig',
    'teams.apps.TeamsConfig',
    'user_preferences.apps.UserPreferencesConfig',
    'asset.apps.AssetConfig',
    'budget_approval',
    'retrospective',
    'behavioral_tracking.apps.BehavioralTrackingConfig',
    'task',
    'alerting.apps.AlertingConfig',
    'dashboard',
    'metric_upload.apps.MetricUploadConfig',
    'report',
    'optimization',
    'facebook_meta',
    'stripe_meta',
    'notion_editor.apps.NotionEditorConfig',
    'tiktok.apps.TikTokConfig',
    'mailchimp',
    'google_ads',
    'klaviyo.apps.KlaviyoConfig',
    'django_prometheus',
    'automationWorkflow.apps.AutomationWorkflowConfig',
    'decision.apps.DecisionConfig',
    'chat.apps.ChatConfig',
    'experiment.apps.ExperimentConfig',
    'client_communication.apps.ClientCommunicationConfig',
    'comments.apps.CommentsConfig',
    'calendars.apps.CalendarConfig',
    'miro.apps.MiroConfig',
    'ad_copy_variation',
    'policy.apps.PolicyConfig',
    'campaign.apps.CampaignConfig',
    'slack_integration.apps.SlackIntegrationConfig',
    'agent.apps.AgentConfig',
    'meetings.apps.MeetingsConfig',
    'notifications.apps.NotificationsConfig',
    'zoom_integration.apps.ZoomIntegrationConfig',
    'linear_integration.apps.LinearIntegrationConfig',
    'google_docs_integration.apps.GoogleDocsIntegrationConfig',
    'google_calendar_integration.apps.GoogleCalendarIntegrationConfig',
    'facebook_integration.apps.FacebookIntegrationConfig',
    'meta_ads.apps.MetaAdsConfig',
    'experience_group',
    'customer',
    'tracking',
    'csm',
    'portal',
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    # Protect PostgreSQL before tenant/auth/custom middleware opens a DB
    # connection. Excess requests wait here instead of failing at max_connections.
    'core.middleware.database_concurrency.DatabaseConcurrencyLimitMiddleware',
    'stripe_meta.middleware.UsageTrackingMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Compress JSON/text responses (big win for bulk endpoints like spreadsheet
    # readCellRange and batch responses). axios sends Accept-Encoding: gzip by
    # default so no frontend change needed. Must be placed before CommonMiddleware.
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.tenant_schema.TenantSchemaMiddleware',
    'authentication.middleware.PasswordRotationMiddleware',
    'core.middleware.project_access.CheckProjectAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'access_control.middleware.authorization.AuthorizationMiddleware', 
    'user_preferences.middleware.user_locale.UserLocaleMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'tracking.middleware.ServerSideTrackingMiddleware',
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

APP_ENV = os.environ.get("APP_ENV") or os.environ.get("DJANGO_ENV") or os.environ.get("ENVIRONMENT") or "development"
APP_ENV = APP_ENV.lower()

PASSWORD_ROTATION_ENABLED = os.environ.get('PASSWORD_ROTATION_ENABLED', 'true').lower() != 'false'
PASSWORD_ROTATION_MAX_ALLOWED_AGE_DAYS = 180
PASSWORD_ROTATION_MAX_AGE_DAYS = min(
    int(os.environ.get('PASSWORD_ROTATION_MAX_AGE_DAYS', '90')),
    PASSWORD_ROTATION_MAX_ALLOWED_AGE_DAYS,
)
PASSWORD_ROTATION_WARNING_DAYS = min(
    int(os.environ.get('PASSWORD_ROTATION_WARNING_DAYS', '7')),
    PASSWORD_ROTATION_MAX_AGE_DAYS,
)

if APP_ENV in {"production", "prod", "staging", "stage"} and not PASSWORD_ROTATION_ENABLED:
    raise ImproperlyConfigured("PASSWORD_ROTATION_ENABLED cannot be false in production or staging.")

ROOT_URLCONF = 'backend.urls'

APPEND_SLASH = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Channels Configuration
ASGI_APPLICATION = 'backend.asgi.application'

# Channel Layers for Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('redis', 6379)],  # Use Redis container in Docker
            # channels_redis defaults this to 100, and that default silently
            # drops messages under load. Every WebSocket connection served by
            # one ASGI process shares a single inbound queue (the Redis key is
            # derived from the part of the channel name before "!", which is
            # per-process, not per-connection), so the whole process gets 100
            # slots between them. When group_send finds the queue full it skips
            # the write, logs one INFO line, and raises nothing — the message is
            # simply never delivered.
            #
            # Measured at 100 concurrent users in one channel:
            #
            #   capacity    drops logged    delivered
            #   100         15,471          78
            #   10,000       5,533          2,568
            #   50,000           0          4,161-4,503
            #
            # Capacity bounds memory because queued messages also expire; see
            # the expiry note below. Redis peaked at 17 MB across the 50,000
            # runs, against 10 MB at 10,000.
            #
            # This is a safety valve, not the fix. The pressure comes from
            # fanning one message out as one publish per recipient; a
            # channel-level group would make it one publish and drop the queue
            # depth by two orders of magnitude.
            "capacity": config('CHANNEL_LAYER_CAPACITY', default=50000, cast=int),
            # The second silent drop, and the one capacity does not cover.
            # channels_redis expires queued messages, and every group_send
            # sweeps each recipient channel with
            # ZREMRANGEBYSCORE(key, 0, now - expiry) before writing. Anything a
            # connection has not read within the window is deleted with no log
            # line and no error — unlike a capacity drop, which at least logs.
            #
            # The default is 60s. Measured with 100 connections in one channel,
            # driving ~1,700 deliveries/s against a ceiling of roughly 1,000/s
            # on a single ASGI process, so the backlog grew past the window:
            #
            #   demand      p95 delivery    deliveries lost
            #   ~1,550/s    33.5s            0 of 99,000
            #   ~1,700/s    60.0s (pinned)   ~12,000 of 148,500 (~8%)
            #
            # The loss was one contiguous block of send order per connection —
            # exactly the interval during which the backlog exceeded 60s — and
            # p95 sat flat on the expiry value. Nothing else registered it:
            # every message was committed, every outbox event published, every
            # socket stayed open, and MessageStatus recorded them delivered.
            #
            # 300s is not headroom for a sustainable overload; a backlog that
            # keeps growing reaches any window eventually. It buys time for a
            # burst or a slow consumer to drain before delivery turns lossy.
            "expiry": config('CHANNEL_LAYER_EXPIRY', default=300, cast=int),
        },
    },
}



# ClamAV Configuration
CLAMAV_HOST = 'clamav'
CLAMAV_PORT = 3310


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB', default='mediajira_db'),
        'USER': config('POSTGRES_USER', default='postgres'),
        'PASSWORD': config('POSTGRES_PASSWORD', default='cocofly4321'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('POSTGRES_PORT', default='5432'),
        # DO NOT set CONN_MAX_AGE here without a connection pooler in front of
        # PostgreSQL. It was measured and reverted:
        #
        # Connection reuse is genuinely attractive on the WebSocket path —
        # opening a connection to this database costs ~51 ms against ~1 ms for a
        # query on an open one, and with CONN_MAX_AGE=60 a 100-connection burst
        # went from 20% refused to 3%, handshake p95 4.8 s to 1.1 s.
        #
        # But Django's ASGI handler runs each HTTP request on its own thread,
        # and a persistent connection is thread-local: it is not closed when the
        # request ends (it is not yet obsolete) and it is not closed when the
        # thread is destroyed. Under 100 concurrent requests that leaks roughly
        # one connection per request — measured 99 of max_connections=100, 90 of
        # them idle, and 94% of message sends then timed out.
        #
        # The safe version of this optimisation is PgBouncer (or raising
        # max_connections to fit the real thread count), not this setting.
        # REMOVED: 'OPTIONS': {'options': '-c search_path=public'}
        # TenantSchemaMiddleware dynamically sets search_path per request
        'OPTIONS': {
            'application_name': config('PG_APPLICATION_NAME', default='django_web'),
        },
        'TEST': {
            'NAME': 'test_mediajira_db',
        }
    }
}

# This is a per-web-process admission limit, not a replacement for PgBouncer.
# Keep headroom for Celery, WebSocket ORM calls, migrations and monitoring.
DATABASE_REQUEST_CONCURRENCY = config(
    'DATABASE_REQUEST_CONCURRENCY',
    default=20,
    cast=int,
)
DATABASE_REQUEST_QUEUE_TIMEOUT_SECONDS = config(
    'DATABASE_REQUEST_QUEUE_TIMEOUT_SECONDS',
    default=30,
    cast=float,
)

USE_SQLITE_FOR_TESTS = config('USE_SQLITE_FOR_TESTS', default=False, cast=bool)
if USE_SQLITE_FOR_TESTS:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.test.sqlite3'),
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'core.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', '简体中文'),
    ('zh-hant', '繁體中文'),
    ('ja', '日本語'),
    ('ko-kr', '한국어'),
]


TIME_ZONE = 'UTC'

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Static files configuration for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File storage root used by metric_upload
FILE_STORAGE_DIR = config(
    'FILE_STORAGE_DIR',
    default=os.path.join(BASE_DIR, 'media')
)

# Agent CSV data directory
AGENT_CSV_DIR = config(
    'AGENT_CSV_DIR',
    default=os.path.join(BASE_DIR, 'agent_data')
)

# Gemini API (replaces Dify for all LLM workflow calls)
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')

# AI-assisted spreadsheet analysis (agent <-> spreadsheet integration).
# Global kill-switch; a per-project toggle (Project.ai_analysis_enabled) and
# per-user, per-spreadsheet consent (spreadsheet.SpreadsheetAiConsent) gate it
# further.
AGENT_SPREADSHEET_AI_ENABLED = config(
    'AGENT_SPREADSHEET_AI_ENABLED', default=True, cast=bool
)
# Hard caps on spreadsheet data handed to an LLM (spreadsheet.providers +
# core.services.file_parser read these at call time).
SPREADSHEET_AI_MAX_ROWS = config('SPREADSHEET_AI_MAX_ROWS', default=500, cast=int)
SPREADSHEET_AI_MAX_COLS = config('SPREADSHEET_AI_MAX_COLS', default=50, cast=int)
SPREADSHEET_AI_MAX_CELLS = config('SPREADSHEET_AI_MAX_CELLS', default=20000, cast=int)
SPREADSHEET_AI_MAX_CELL_CHARS = config(
    'SPREADSHEET_AI_MAX_CELL_CHARS', default=2000, cast=int
)
# Gemini HTTP guardrails (core.services.gemini_client).
GEMINI_TIMEOUT_SECONDS = config('GEMINI_TIMEOUT_SECONDS', default=75, cast=int)
GEMINI_TOTAL_DEADLINE_SECONDS = config(
    'GEMINI_TOTAL_DEADLINE_SECONDS', default=150, cast=int
)
GEMINI_CB_THRESHOLD = config('GEMINI_CB_THRESHOLD', default=5, cast=int)
GEMINI_CB_WINDOW_SECONDS = config('GEMINI_CB_WINDOW_SECONDS', default=60, cast=int)
GEMINI_CB_COOLDOWN_SECONDS = config('GEMINI_CB_COOLDOWN_SECONDS', default=30, cast=int)

# Dify LLM Platform integration (kept for reference / backward compat)
DIFY_API_URL = config('DIFY_API_URL', default='')
DIFY_API_KEY = config('DIFY_API_KEY', default='')
DIFY_CHAT_API_KEY = config('DIFY_CHAT_API_KEY', default='')
DIFY_MIRO_API_KEY = config('DIFY_MIRO_API_KEY', default='')
DIFY_CALENDAR_API_KEY = config('DIFY_CALENDAR_API_KEY', default='')
DIFY_COLUMN_DETECTION_API_KEY = config('DIFY_COLUMN_DETECTION_API_KEY', default='')
DIFY_CRITERIA_API_KEY = config('DIFY_CRITERIA_API_KEY', default='')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:80",
    "http://127.0.0.1:80",
] + [
    o.strip() for o in config('CORS_EXTRA_ORIGINS', default='').split(',')
    if o.strip()
]

CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins - Required for ngrok and external domains
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
] + [
    o.strip() for o in config('CSRF_EXTRA_ORIGINS', default='').split(',')
    if o.strip()
]

# Session Configuration for OAuth
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow session cookies for OAuth redirects
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = True

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Use tenant-aware JWT authentication to handle multi-tenant schema switching
        'core.authentication.TenantAwareJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'EXCEPTION_HANDLER': 'calendars.exceptions.calendar_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'chat_message_write': config('CHAT_MESSAGE_WRITE_THROTTLE_RATE', default='60/minute'),
        'chat_reaction': config('CHAT_REACTION_THROTTLE_RATE', default='120/minute'),
        'spreadsheet_ws_ticket': config(
            'SPREADSHEET_WS_TICKET_THROTTLE_RATE',
            default='60/minute',
        ),
    },
}

SPREADSHEET_WS_CONNECTION_MAX_SECONDS = config(
    'SPREADSHEET_WS_CONNECTION_MAX_SECONDS',
    default=3600,
    cast=int,
)

CHAT_REVOKE_WINDOW_MINUTES = config('CHAT_REVOKE_WINDOW_MINUTES', default=2, cast=int)

from datetime import timedelta

# Import Celery app to ensure it's loaded when Django starts
from .celery import app as celery_app

__all__ = ('celery_app',)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=4),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=4),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = config('TIME_ZONE', default='UTC')
broker_connection_retry_on_startup = True

# Keep latency-sensitive chat delivery isolated from notifications, offline
# recovery, scheduled sends, integrations, reports, and other default tasks.
# Dedicated workers for these queues are defined in the compose/deployment
# configuration. Missing queues are created by Celery when first published.
CELERY_TASK_ROUTES = {
    'chat.tasks.notify_new_message': {'queue': 'chat.realtime'},
    'chat.tasks.notify_reaction_update': {'queue': 'chat.realtime'},
    'chat.tasks.notify_pin_update': {'queue': 'chat.realtime'},
    'chat.tasks.finalize_presence_offline': {'queue': 'chat.realtime'},
    'chat.tasks.send_typing_indicator': {'queue': 'chat.realtime'},
    'chat.tasks.update_message_status_task': {'queue': 'chat.realtime'},
    'chat.tasks.notify_message_recipients': {'queue': 'chat.notifications'},
    'chat.tasks.deliver_message_task': {'queue': 'chat.delivery'},
    'chat.tasks.send_scheduled_message': {'queue': 'chat.delivery'},
    # A link preview waits on a third-party site, so it gets its own low-priority
    # queue with its own worker: one slow host must never sit in front of message
    # delivery. Every deployment file consumes chat.link_previews — a queue nobody
    # consumes would silently pile up previews, so they must stay in step.
    'chat.tasks.fetch_link_preview_task': {'queue': 'chat.link_previews'},
    'chat.tasks.prune_link_previews': {'queue': 'chat.link_previews'},
}

# --- Link previews (MED-279) -------------------------------------------------
# How long an answer is reused before the URL is fetched again. Success and
# failure are separate on purpose: a page that resolved fine is worth holding for
# a day, but a host that timed out may well be back within the hour, and a URL the
# safety guard refused is not going to become safe on its own.
LINK_PREVIEW_SUCCESS_TTL_HOURS = config('LINK_PREVIEW_SUCCESS_TTL_HOURS', default=24, cast=int)
LINK_PREVIEW_FAILURE_TTL_HOURS = config('LINK_PREVIEW_FAILURE_TTL_HOURS', default=1, cast=int)
LINK_PREVIEW_BLOCKED_TTL_HOURS = config('LINK_PREVIEW_BLOCKED_TTL_HOURS', default=24, cast=int)

# A pending row older than this is treated as abandoned, so a worker that died
# mid-fetch cannot wedge a URL forever.
LINK_PREVIEW_CLAIM_TTL_MINUTES = config('LINK_PREVIEW_CLAIM_TTL_MINUTES', default=5, cast=int)

# Caching stops the same URL being fetched twice, but nothing stops one account
# posting many *different* URLs, which is how this feature could be turned into a
# request amplifier. Cache hits are free; only fetches of new URLs count.
LINK_PREVIEW_RATE_LIMIT_PER_MINUTE = config('LINK_PREVIEW_RATE_LIMIT_PER_MINUTE', default=5, cast=int)

# Rows older than this are pruned daily; without it the table only ever grows.
LINK_PREVIEW_PRUNE_AFTER_DAYS = config('LINK_PREVIEW_PRUNE_AFTER_DAYS', default=30, cast=int)

# Bound concurrent Channels publications inside one Celery/ASGI process so a
# large group cannot create an unbounded Redis command burst.
CHAT_FANOUT_CONCURRENCY = config('CHAT_FANOUT_CONCURRENCY', default=25, cast=int)

# A SubscriptionRegistry normally runs on its owning ASGI event loop. Calls
# submitted from another OS thread must not wait forever if that loop stalls or
# shuts down between availability checks.
CHAT_SUBSCRIPTION_THREAD_CALL_TIMEOUT_SECONDS = config(
    'CHAT_SUBSCRIPTION_THREAD_CALL_TIMEOUT_SECONDS',
    default=5.0,
    cast=float,
)

# Publish a chat message once to a per-chat channel-layer group instead of once
# per recipient.
#
# Off by default. It changes where the authorisation decision lives: today the
# server picks recipients per message, and a connection can only ever receive
# from its own personal group. With chat groups, membership of
# `chat_<id>` *is* the entitlement, so a stale membership means someone reads a
# channel they were removed from. Turn it on only where the revocation path
# (ChatService.invalidate_presence_recipients_for_chat -> chat_membership_changed
# -> the consumer re-syncing its groups) has been exercised.
#
# Duplicate delivery is handled, not tolerated. A group publish reaches whoever
# is in the group at that moment, which can include a connection that arrived
# after the claim — its status row is still 'sent', so the delivery task sends
# it again. Every write to a socket now goes through one method that drops a
# message id it has already sent, so a race between the realtime fan-out, the
# delivery task and reconnect recovery cannot reach the client.
#
# Measured over three consecutive 100-user runs on a barrier-enforced load test
# (chat_ready_after_barrier = 0, meaning every client was ready before any of
# them wrote):
#
#   flag on   9,900/9,900 delivered, 0 duplicates, delivery p95 4.69-5.10s
#   flag off  9,900/9,900 delivered, 0 duplicates, delivery p95 9.40s
#
# Earlier runs of this flag looked non-deterministic, at 6,983-9,900 delivered.
# That was the load test rather than the feature: its warm-up defaulted to zero,
# so the first ready client sent while later clients were still connecting, and
# a group publish cannot reach a socket that does not exist yet. Per-recipient
# fan-out hid it because an absent user is simply not claimed and picks the
# message up on connect.
#
# Still off by default pending a decision, not pending a fix: turning it on is
# a behaviour change on the delivery path and the revocation route above should
# be exercised in a preview environment first.
CHAT_CHANNEL_GROUPS_ENABLED = config('CHAT_CHANNEL_GROUPS_ENABLED', default=False, cast=bool)

# Bound independent post-accept ORM work. One thread serialized 100 sockets;
# an unbounded executor would instead exhaust PostgreSQL connections.
CHAT_CONNECTION_INIT_CONCURRENCY = config(
    'CHAT_CONNECTION_INIT_CONCURRENCY',
    default=10,
    cast=int,
)

# Recovery is paged to keep individual queries bounded, but one reconnect must
# not silently stop after the first 50 durable messages.
CHAT_RECONNECT_RECOVERY_MAX_MESSAGES = config(
    'CHAT_RECONNECT_RECOVERY_MAX_MESSAGES',
    default=500,
    cast=int,
)

# That recovery only finds rows still marked 'sent', and a message is marked
# delivered when it is handed to the channel layer rather than when a socket
# receives it. The two are not the same: a queued message the connection does
# not read within the channel layer's expiry is deleted silently, and its row
# already says delivered, so nothing ever resends it.
#
# So a reconnect also replays what was marked delivered recently. Anything the
# client already has is dropped on arrival — the frontend keys messages by id —
# which makes replaying more than necessary the cheap side of this trade.
#
# Keep the window at or above the channel layer expiry: it is the interval in
# which a publish can be discarded after being recorded as delivered. Below it,
# the hole reopens for the difference.
CHAT_RECONNECT_REPLAY_SECONDS = config(
    'CHAT_RECONNECT_REPLAY_SECONDS',
    default=300,
    cast=int,
)
CHAT_RECONNECT_REPLAY_MAX_MESSAGES = config(
    'CHAT_RECONNECT_REPLAY_MAX_MESSAGES',
    default=100,
    cast=int,
)

# Celery Beat Configuration for Periodic Tasks
CELERY_BEAT_SCHEDULE = {
    'dispatch-pending-chat-outbox': {
        'task': 'chat.tasks.dispatch_pending_chat_outbox',
        'schedule': timedelta(seconds=1),
        'options': {'queue': 'celery'},
    },
    # 'reset-daily-usage': {   # disabled — UsageDaily replaced by token-based billing
    #     'task': 'stripe_meta.tasks.reset_daily_usage',
    #     'schedule': crontab(hour=0, minute=0),
    #     'options': {'timezone': 'UTC'},
    # },
    'aggregate-monthly-llm-cost': {
        'task': 'stripe_meta.tasks.aggregate_monthly_llm_cost',
        'schedule': crontab(hour=2, minute=0),   # daily 02:00 UTC
        'options': {'timezone': 'UTC'},
    },
    'check-fair-use-alerts': {
        'task': 'stripe_meta.tasks.check_fair_use_alerts',
        'schedule': crontab(hour=3, minute=0),   # daily 03:00 UTC
        'options': {'timezone': 'UTC'},
    },
    'report-overage-to-stripe': {
        'task': 'stripe_meta.tasks.report_overage_to_stripe',
        # 1st of month, 01:00 UTC — reports the PREVIOUS (completed) month, so no
        # late-month overage is missed and an off-schedule run targets the right month.
        'schedule': crontab(hour=1, minute=0, day_of_month=1),
        'options': {'timezone': 'UTC'},
    },
    'cleanup-expired-tiktok-previews': {
        'task': 'tiktok.tasks.cleanup_expired_previews',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 02:00 UTC (low traffic period)
        'options': {'timezone': 'UTC'}
    },
    'cleanup-orphaned-chat-attachments': {
        'task': 'chat.tasks.cleanup_orphaned_attachments',
        'schedule': crontab(hour=4, minute=0),  # daily 04:00 UTC (low traffic period)
        'options': {'timezone': 'UTC'},
    },
    'prune-link-previews': {
        'task': 'chat.tasks.prune_link_previews',
        'schedule': crontab(hour=4, minute=30),  # daily 04:30 UTC, after the sweep above
        'options': {'timezone': 'UTC'},
    },
    'google-calendar-import-every-15-min': {
        'task': 'google_calendar_integration.tasks.sync_all_google_calendar_imports',
        'schedule': timedelta(minutes=15),
        'options': {'timezone': 'UTC'},
    },
    'meta-ads-hourly-sync': {
        'task': 'meta_ads.tasks.sync_all_meta_connections',
        'schedule': crontab(minute=7),  # offset from other :00 hourly tasks
        'options': {'timezone': 'UTC'},
    },
    'meta-ads-daily-fan-out': {
        'task': 'meta_ads.tasks.sync_all_active_ad_accounts',
        'schedule': crontab(hour=6, minute=0),  # daily at 06:00 UTC
        'options': {'timezone': 'UTC'},
    },
    'expire-stale-tracking-sessions': {
        'task': 'tracking.tasks.expire_stale_sessions',
        'schedule': crontab(minute='*/5'),
        'options': {'timezone': 'UTC'},
    },
    'purge-old-tracking-data': {
        'task': 'tracking.tasks.purge_old_data',
        'schedule': crontab(hour=3, minute=0),
        'options': {'timezone': 'UTC'},
    },
    # Notification tasks
    'fire-calendar-reminders': {
        'task': 'notifications.tasks.fire_calendar_reminders',
        'schedule': timedelta(minutes=1),
        'options': {'timezone': 'UTC'},
    },
    'fire-task-overdue-notifications': {
        'task': 'notifications.tasks.fire_task_overdue_notifications',
        'schedule': timedelta(hours=1),
        'options': {'timezone': 'UTC'},
    },
    'fire-decision-deadline-notifications': {
        'task': 'notifications.tasks.fire_decision_deadline_notifications',
        'schedule': timedelta(hours=12),
        'options': {'timezone': 'UTC'},
    },
    'fire-meeting-starting-soon-notifications': {
        'task': 'notifications.tasks.fire_meeting_starting_soon_notifications',
        'schedule': timedelta(minutes=5),
        'options': {'timezone': 'UTC'},
    },
    'fire-message-reminders': {
        'task': 'notifications.tasks.fire_message_reminders',
        'schedule': timedelta(minutes=1),
        'options': {'timezone': 'UTC'},
    },
    # Agent workflow trigger tasks
    'agent-check-polling-triggers': {
        'task': 'agent.tasks.check_polling_triggers',
        'schedule': timedelta(minutes=5),
        'options': {'timezone': 'UTC'},
    },
    'agent-check-scheduled-triggers': {
        'task': 'agent.tasks.check_scheduled_triggers',
        'schedule': timedelta(minutes=1),
        'options': {'timezone': 'UTC'},
    },
    'agent-cleanup-old-trigger-logs': {
        'task': 'agent.tasks.cleanup_old_trigger_logs',
        'schedule': crontab(hour=2, minute=0),
        'options': {'timezone': 'UTC'},
    },
    # CSM: auto-resolve tickets stuck in Pending Customer Response
    'csm-auto-resolve-pending-tickets': {
        'task': 'csm.tasks.auto_resolve_pending_tickets',
        'schedule': crontab(hour=1, minute=30),  # daily 01:30 UTC
        'options': {'timezone': 'UTC'},
    },
    # CSM: alert on SLA breaches (first response / resolution)
    'csm-notify-sla-breaches': {
        'task': 'csm.tasks.notify_sla_breaches',
        'schedule': crontab(minute='*/15'),
        'options': {'timezone': 'UTC'},
    },
}

# Shared secret for the platform-native cron endpoint that triggers the
# daily Meta ads fan-out. Empty string disables the endpoint (always 401).
INTERNAL_CRON_SECRET = config('INTERNAL_CRON_SECRET', default='')

# Redis Configuration
REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

# Notification SSE replay protection. Replay is delivered in bounded batches,
# and repeated replay connections are limited per authenticated user using a
# rolling Redis window.
NOTIFICATION_SSE_REPLAY_BATCH_SIZE = config(
    'NOTIFICATION_SSE_REPLAY_BATCH_SIZE', default=500, cast=int
)
NOTIFICATION_SSE_REPLAY_RATE_LIMIT = config(
    'NOTIFICATION_SSE_REPLAY_RATE_LIMIT', default=5, cast=int
)
NOTIFICATION_SSE_REPLAY_RATE_WINDOW_SECONDS = config(
    'NOTIFICATION_SSE_REPLAY_RATE_WINDOW_SECONDS', default=30, cast=int
)

# Cache Configuration (for online status, etc.)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/1',  # Use db=1 (separate from Celery's db=0)
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'mediajira',  # Prefix all cache keys
        'TIMEOUT': None,  # Default timeout (None = no expiration)
    }
}

# Kafka Configuration
# Kafka broker address - automatically selects INTERNAL (containers) or EXTERNAL (host/CI) listener
KAFKA_BROKER = config('KAFKA_BROKER', default='kafka:9092')  # Default to INTERNAL listener for containers
KAFKA_ENABLED = config('KAFKA_ENABLED', default=True, cast=bool)  # Feature flag to enable/disable Kafka

# Kafka Topic Names (following domain.action.format convention)
# See devops/kafka/topics.yaml for complete topic definitions
KAFKA_TOPICS = {
    # Campaign domain
    'CAMPAIGN_CREATED': 'campaign.created.json',
    'CAMPAIGN_UPDATED': 'campaign.updated.json',
    'CAMPAIGN_DELETED': 'campaign.deleted.json',
    'CAMPAIGN_STATUS_CHANGED': 'campaign.status_changed.json',
    
    # Asset domain
    'ASSET_CREATED': 'asset.created.json',
    'ASSET_UPDATED': 'asset.updated.json',
    'ASSET_DELETED': 'asset.deleted.json',
    'ASSET_STATUS_CHANGED': 'asset.status_changed.json',
    
    # Task domain
    'TASK_CREATED': 'task.created.json',
    'TASK_UPDATED': 'task.updated.json',
    'TASK_STATUS_CHANGED': 'task.status_changed.json',
    'TASK_DELETED': 'task.deleted.json',
    
    # Retrospective domain
    'RETROSPECTIVE_CREATED': 'retrospective.created.json',
    'RETROSPECTIVE_COMPLETED': 'retrospective.completed.json',
    'RETROSPECTIVE_UPDATED': 'retrospective.updated.json',
    
    # Budget Approval domain
    'BUDGET_REQUEST_CREATED': 'budget_approval.request_created.json',
    'BUDGET_REQUEST_APPROVED': 'budget_approval.request_approved.json',
    'BUDGET_REQUEST_REJECTED': 'budget_approval.request_rejected.json',
    
    # Report domain
    
    # Metric Upload domain
    'METRIC_UPLOADED': 'metric_upload.uploaded.json',
    'METRIC_PROCESSED': 'metric_upload.processed.json',
    
    # Optimization domain
    'OPTIMIZATION_EXPERIMENT_CREATED': 'optimization.experiment_created.json',
    'OPTIMIZATION_EXPERIMENT_COMPLETED': 'optimization.experiment_completed.json',
    
    # Project domain (core)
    'PROJECT_CREATED': 'core.project_created.json',
    'PROJECT_UPDATED': 'core.project_updated.json',
    'PROJECT_DELETED': 'core.project_deleted.json',
    
    # Organization domain (core)
    'ORGANIZATION_CREATED': 'core.organization_created.json',
    'ORGANIZATION_UPDATED': 'core.organization_updated.json',
    
    # Team domain
    'TEAM_CREATED': 'teams.team_created.json',
    'TEAM_UPDATED': 'teams.team_updated.json',
    'TEAM_MEMBER_ADDED': 'teams.member_added.json',
    'TEAM_MEMBER_REMOVED': 'teams.member_removed.json',
    
    # User domain (authentication/core)
    'USER_CREATED': 'authentication.user_created.json',
    'USER_UPDATED': 'authentication.user_updated.json',
    'USER_LOGGED_IN': 'authentication.user_logged_in.json',
    
    # Access Control domain
    'PERMISSION_GRANTED': 'access_control.permission_granted.json',
    'PERMISSION_REVOKED': 'access_control.permission_revoked.json',
    'ROLE_ASSIGNED': 'access_control.role_assigned.json',
    
    # Integration domains (optional - enable as needed)
    'FACEBOOK_META_AD_CREATED': 'facebook_meta.ad_created.json',
    'GOOGLE_ADS_CREATED': 'google_ads.ad_created.json',
    'TIKTOK_CREATIVE_CREATED': 'tiktok.creative_created.json',
    'MAILCHIMP_CAMPAIGN_CREATED': 'mailchimp.campaign_created.json',
    'KLAVIYO_EMAIL_SENT': 'klaviyo.email_sent.json',
    'STRIPE_PAYMENT_PROCESSED': 'stripe_meta.payment_processed.json',
    'NOTION_DOCUMENT_CREATED': 'notion_editor.document_created.json',
    
    # Workflow domain
    'WORKFLOW_TRIGGERED': 'workflows.workflow_triggered.json',
    'WORKFLOW_COMPLETED': 'workflows.workflow_completed.json',
}

# Internal Webhook Configuration
INTERNAL_WEBHOOK_TOKEN = config('INTERNAL_WEBHOOK_TOKEN', default='default_token_for_dev')
INTERNAL_WEBHOOK_ENABLED = config('INTERNAL_WEBHOOK_ENABLED', default=True, cast=bool)

# Stripe Configuration
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='sk')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='pk')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='wh')
# Token-billing Stripe price IDs (env-driven, no hardcoded IDs)
STRIPE_TEAM_BASE_PRICE_ID = os.environ.get('STRIPE_TEAM_BASE_PRICE_ID', '')
STRIPE_TEAM_EXTRA_SEAT_PRICE_ID = os.environ.get('STRIPE_TEAM_EXTRA_SEAT_PRICE_ID', '')
STRIPE_TEAM_OVERAGE_PRICE_ID = os.environ.get('STRIPE_TEAM_OVERAGE_PRICE_ID', '')
# Per-model token multipliers (relative to sonnet baseline = 1.0)
MODEL_TOKEN_MULTIPLIER = {
    'claude-sonnet-4-20250514': 1.0,
    'claude-sonnet-4-5': 1.0,
    'claude-haiku-4-5': 0.2,
    'claude-opus-4-6': 5.0,
    'gemini-2.5-flash-lite': 0.15,
}
# Actual API cost table in cents per 1M tokens (for LLMCallLog cost_cents)
LLM_PRICE_TABLE = {
    'claude-sonnet-4-20250514': {'input': 300, 'output': 1500},
    'claude-sonnet-4-5': {'input': 300, 'output': 1500},
    'claude-haiku-4-5': {'input': 80, 'output': 400},
    'claude-opus-4-6': {'input': 1500, 'output': 7500},
    'gemini-2.5-flash-lite': {'input': 10, 'output': 40},
}
FAIR_USE_THRESHOLD_RATIO = 0.30   # alert when user > 30% of org quota
FREE_USER_MAX_COST_CENTS = 200    # safety cap for fair-use alert on Free tier

# Organization Access Token Configuration
ORGANIZATION_ACCESS_TOKEN_SECRET_KEY = config('ORGANIZATION_ACCESS_TOKEN_SECRET_KEY', default='52r(=liv3ro&zsuau-doa(wekq-(x^&y8(b$5h@k(g(c9&jlmp')
ORGANIZATION_ACCESS_TOKEN_ENCRYPTION_KEY = config('ORGANIZATION_ACCESS_TOKEN_ENCRYPTION_KEY', default='jtBsdl7-HVKnF61JnesSM0xpqB-vkAXboBbIRawVUhU=')

# Field-level encryption keys for OAuth tokens and API secrets stored in the DB.
# Format: comma-separated list of "key_id:fernet_base64_key" pairs.
# The FIRST entry is the active key (used for new encryptions).
# All entries are tried on decryption, enabling zero-downtime key rotation.
# To generate a new key:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Then prepend "new_id:new_key," to this setting and run the reencrypt_secret_fields task.
FIELD_ENCRYPTION_KEYS = config(
    'FIELD_ENCRYPTION_KEYS',
    default='v1:VeVFSKpPagu0DlIXDGJl_3bcyVc7uSwzChn2kDCRims=',
)

# Email Configuration
# For development, use console backend to print emails to console
# For production, configure SMTP settings below
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)

# SMTP Email Settings (for production)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@mediajira.com')

# Frontend URL for invitation links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Google OAuth Configuration
def _get_google_env(primary_key, fallback_key):
    primary_value = config(primary_key, default='').strip()
    if primary_value:
        return primary_value
    return config(fallback_key, default='').strip()

GOOGLE_OAUTH_CLIENT_ID = _get_google_env('GOOGLE_CLIENT_ID', 'GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = _get_google_env('GOOGLE_CLIENT_SECRET', 'GOOGLE_OAUTH_CLIENT_SECRET')
GOOGLE_OAUTH_REDIRECT_URI = _get_google_env('GOOGLE_OAUTH_REDIRECT_URI', 'GOOGLE_REDIRECT_URI')
GOOGLE_CALENDAR_OAUTH_REDIRECT_URI = config(
    'GOOGLE_CALENDAR_OAUTH_REDIRECT_URI',
    default='http://localhost:8000/api/google-calendar/callback/',
).strip()

# Notion OAuth Configuration
NOTION_OAUTH_CLIENT_ID = config('NOTION_CLIENT_ID', default='').strip()
NOTION_OAUTH_CLIENT_SECRET = config('NOTION_CLIENT_SECRET', default='').strip()
NOTION_OAUTH_REDIRECT_URI = config('NOTION_OAUTH_REDIRECT_URI', default='').strip()

# Logging Configuration
import logging
import logging.config
import json_log_formatter

formatter = json_log_formatter.JSONFormatter()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'redact_secrets': {
            '()': 'core.services.log_redaction.RedactSecretsFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['redact_secrets'],
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            'filters': ['redact_secrets'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
        'filters': ['redact_secrets'],
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'task': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce Celery debug output
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce task discovery debug output
            'propagate': False,
        },
    },
}

import logging
logger = logging.getLogger(__name__)
OTEL_ENABLED = config('OTEL_ENABLED', default=False, cast=bool)
JAEGER_AGENT_HOST = config('JAEGER_AGENT_HOST', default=None)
if OTEL_ENABLED and JAEGER_AGENT_HOST:
    try:
        from opentelemetry import trace
        from opentelemetry.sdk.trace import TracerProvider
        from opentelemetry.sdk.trace.export import BatchSpanProcessor
        from opentelemetry.exporter.jaeger.thrift import JaegerExporter
        from opentelemetry.instrumentation.django import DjangoInstrumentor
        from opentelemetry.instrumentation.psycopg2 import Psycopg2Instrumentor

        trace.set_tracer_provider(TracerProvider())

        jaeger_agent_port = config('JAEGER_AGENT_PORT', default=6831, cast=int)
        jaeger_exporter = JaegerExporter(
            agent_host_name=JAEGER_AGENT_HOST,
            agent_port=jaeger_agent_port,
        )

        trace.get_tracer_provider().add_span_processor(BatchSpanProcessor(jaeger_exporter))

        DjangoInstrumentor().instrument()
        Psycopg2Instrumentor().instrument()
        logger.info(f"OpenTelemetry enabled with Jaeger exporter at {JAEGER_AGENT_HOST}:{jaeger_agent_port}")
    except Exception as e:
        logger.warning(f"Failed to initialize OpenTelemetry: {e}. Continuing without tracing.")
else:
    if not OTEL_ENABLED:
        logger.debug("OpenTelemetry is disabled. Set OTEL_ENABLED=True and JAEGER_AGENT_HOST to enable.")
    elif not JAEGER_AGENT_HOST:
        logger.debug("OpenTelemetry is enabled but JAEGER_AGENT_HOST is not set. Set JAEGER_AGENT_HOST to enable Jaeger exporter.")

# Slack Configuration
SLACK_CLIENT_ID = config('SLACK_CLIENT_ID', default='')
SLACK_CLIENT_SECRET = config('SLACK_CLIENT_SECRET', default='')
SLACK_SIGNING_SECRET = config('SLACK_SIGNING_SECRET', default='')
SLACK_REDIRECT_URI = config('SLACK_REDIRECT_URI', default='http://localhost/slack/callback')

# Facebook / Meta Integration (Marketing API + Facebook Login for Business)
FB_APP_ID = config('FB_APP_ID', default='')
FB_APP_SECRET = config('FB_APP_SECRET', default='')
FB_CONFIG_ID = config('FB_CONFIG_ID', default='')
FB_API_VERSION = config('FB_API_VERSION', default='v22.0')
FB_REDIRECT_URI = config('FB_REDIRECT_URI', default='http://localhost/api/facebook_integration/callback/')

# Meetings (SMP-484): when True, creating a meeting requires at least one participant_user_ids entry
MEETINGS_REQUIRE_PARTICIPANTS_AT_CREATE = config(
    'MEETINGS_REQUIRE_PARTICIPANTS_AT_CREATE',
    default=False,
    cast=bool,
)

ZOOM_CLIENT_ID     = os.environ.get("ZOOM_CLIENT_ID", "")
ZOOM_CLIENT_SECRET = os.environ.get("ZOOM_CLIENT_SECRET", "")
ZOOM_REDIRECT_URI  = os.environ.get("ZOOM_REDIRECT_URI", "")
# Webhook only: Secret Token from Zoom Marketplace app → Feature → Webhooks (not OAuth client secret).
ZOOM_WEBHOOK_SECRET_TOKEN = os.environ.get("ZOOM_WEBHOOK_SECRET_TOKEN", "")

# Linear OAuth
LINEAR_CLIENT_ID = (os.environ.get("LINEAR_CLIENT_ID") or "").strip()
LINEAR_CLIENT_SECRET = (os.environ.get("LINEAR_CLIENT_SECRET") or "").strip()
LINEAR_REDIRECT_URI = (os.environ.get("LINEAR_REDIRECT_URI") or "").strip()

# Tracking module config (SMP-546)
TRACKING_IDLE_SECONDS = config('TRACKING_IDLE_SECONDS', default=120, cast=int)
TRACKING_HEARTBEAT_SECONDS = config('TRACKING_HEARTBEAT_SECONDS', default=30, cast=int)
TRACKING_SESSION_TIMEOUT_SECONDS = config('TRACKING_SESSION_TIMEOUT_SECONDS', default=900, cast=int)
TRACKING_EVENT_FLUSH_SECONDS = config('TRACKING_EVENT_FLUSH_SECONDS', default=10, cast=int)
TRACKING_EVENT_RETENTION_DAYS = config('TRACKING_EVENT_RETENTION_DAYS', default=90, cast=int)
TRACKING_SESSION_RETENTION_DAYS = config('TRACKING_SESSION_RETENTION_DAYS', default=180, cast=int)
TRACKING_HANDLERS = [
    'task.tracking_handlers.handle_task_request',
]
