# Generated by Django 4.2.30 on 2026-09-19 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_merge_0023_sessions_and_ai'),
        ('experience_group', '0002_experiencegroup_slug'),
        ('csm', '0026_alter_slapolicy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guidance_type', models.CharField(choices=[('handoff', 'Handoff'), ('suggested_reply', 'Suggested Reply'), ('escalation_procedure', 'Escalation Procedure'), ('process_note', 'Process Note')], max_length=32)),
                ('trigger_description', models.TextField()),
                ('recommended_response', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csm_guidance_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csm_guidance_entries', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceEntryExperienceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_group_links', to='csm.guidanceentry')),
                ('experience_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_links', to='experience_group.experiencegroup')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['experience_group', 'display_order'], name='csm_geg_eg_order_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='guidanceentryexperiencegroup',
            constraint=models.UniqueConstraint(fields=('entry', 'experience_group'), name='csm_geg_unique_entry_eg'),
        ),
    ]
