# Generated by Django 4.2.30 on 2026-09-24 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_0023_sessions_and_ai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience_group', '0002_experiencegroup_slug'),
        ('csm', '0026_alter_slapolicy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('match_mode', models.CharField(choices=[('all', 'All conditions'), ('any', 'Any condition')], default='all', max_length=8)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('action_type', models.CharField(choices=[('route_to_queue', 'Route to queue')], default='route_to_queue', max_length=32)),
                ('add_tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experience_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='experience_group.experiencegroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='core.project')),
                ('target_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='csm.queue')),
            ],
            options={
                'ordering': ['experience_group', 'position', 'id'],
                'indexes': [models.Index(fields=['experience_group', 'position'], name='csm_rr_eg_pos_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='routingrule',
            constraint=models.UniqueConstraint(fields=('experience_group', 'name'), name='csm_rr_unique_name_per_eg'),
        ),
    ]
