# Generated by Django 4.2.30 on 2026-09-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csm', '0027_guidance_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationQualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reviewer_name', models.CharField(blank=True, default='', max_length=200)),
                ('rating', models.CharField(choices=[('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('poor', 'Poor')], max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-reviewed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['queue', 'started_at'], name='csm_conv_queue_started_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='csm_conv_status_idx'),
        ),
        migrations.AddField(
            model_name='conversationqualityreview',
            name='agent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csm_quality_reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationqualityreview',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to='csm.conversation'),
        ),
        migrations.AddField(
            model_name='conversationqualityreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csm_quality_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversationqualityreview',
            index=models.Index(fields=['reviewed_at'], name='csm_cqr_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationqualityreview',
            index=models.Index(fields=['agent_user', 'reviewed_at'], name='csm_cqr_agent_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationqualityreview',
            index=models.Index(fields=['rating'], name='csm_cqr_rating_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationqualityreview',
            constraint=models.UniqueConstraint(fields=('conversation', 'reviewer'), name='csm_cqr_uniq_conversation_reviewer'),
        ),
    ]
