# Generated by Django 4.2.30 on 2026-10-03 10:30

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_0023_sessions_and_ai'),
        ('csm', '0029_routing_rules'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routingrule',
            name='csm_rr_eg_pos_idx',
        ),
        migrations.AlterField(
            model_name='csminvitation',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csm_invitations', to='core.team'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_users', to='core.team'),
        ),
        migrations.AlterField(
            model_name='queueteam',
            name='team',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='queue_assignments', to='core.team'),
        ),
        migrations.AlterField(
            model_name='quickreplytemplate',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, only members of this team can see the template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_reply_templates', to='core.team'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='core.project'),
        ),
        migrations.AddConstraint(
            model_name='routingrule',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('experience_group', 'position'), name='csm_rr_unique_position_per_eg'),
        ),
    ]
