# Generated by Django 4.2.30 on 2026-09-25 10:57

from django.db import migrations, models
import facebook_integration.models


def backfill_project_schemas(apps, schema_editor):
    """Match legacy public projects by org + slug, never by a tenant-local ID."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    import re
    from psycopg2 import sql

    accounts = apps.get_model('facebook_integration', 'MetaAdAccount')
    linked = accounts.objects.using(schema_editor.connection.alias).filter(
        project__organization__isnull=False, project_schema='public',
    ).select_related('project__organization')
    with schema_editor.connection.cursor() as cursor:
        for account in linked.iterator():
            project = account.project
            schema = 'org_' + re.sub(r'[^a-zA-Z0-9]', '_', project.organization.slug)
            cursor.execute('SELECT to_regclass(%s)', [f'{schema}.core_project'])
            if cursor.fetchone()[0] is None:
                continue
            cursor.execute(
                sql.SQL('SELECT id FROM {}.core_project WHERE slug = %s AND organization_id = %s').format(
                    sql.Identifier(schema),
                ),
                [project.slug, project.organization_id],
            )
            match = cursor.fetchone()
            if match:
                accounts.objects.using(schema_editor.connection.alias).filter(pk=account.pk).update(
                    project_id=match[0], project_schema=schema,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_0023_sessions_and_ai'),
        ('facebook_integration', '0002_backfill_encrypt_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaadaccount',
            name='project_schema',
            field=models.CharField(default='public', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='metaadaccount',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=facebook_integration.models.unlink_project_accounts, related_name='linked_meta_accounts', to='core.project'),
        ),
        migrations.RunPython(backfill_project_schemas, migrations.RunPython.noop),
    ]
