# Generated by Django 4.2.23 on 2026-09-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaigntemplate_slug'),
        ('optimization', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPacingForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_configured', 'Not Configured'), ('not_started', 'Not Started'), ('no_data', 'No Data'), ('under_pacing', 'Under Pacing'), ('on_track', 'On Track'), ('over_pacing', 'Over Pacing')], default='no_data', help_text='Pacing verdict for the campaign', max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('missing_budget', 'Missing Budget'), ('missing_end_date', 'Missing End Date'), ('missing_budget_and_end_date', 'Missing Budget And End Date'), ('invalid_period', 'Invalid Period'), ('no_linked_spend', 'No Linked Spend')], default='', help_text='Why no actionable forecast is available (blank when one is)', max_length=32)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget the forecast was computed against', max_digits=15, null=True)),
                ('spend_to_date', models.DecimalField(decimal_places=2, default=0, help_text='Actual spend from campaign start through the computed date', max_digits=15)),
                ('expected_spend_to_date', models.DecimalField(blank=True, decimal_places=2, help_text='Spend a perfectly linear burn would have reached by now', max_digits=15, null=True)),
                ('projected_total_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Forecast spend at period end if current pace continues', max_digits=15, null=True)),
                ('suggested_daily_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Baseline daily cap that would land exactly on budget', max_digits=15, null=True)),
                ('avg_daily_spend', models.DecimalField(decimal_places=2, default=0, help_text='Trailing average daily spend used to project forward', max_digits=15)),
                ('pace_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='projected_total_spend / budget (1.0 lands exactly on budget)', max_digits=8, null=True)),
                ('total_days', models.IntegerField(default=0, help_text='Length of the campaign period in days (inclusive)')),
                ('days_elapsed', models.IntegerField(default=0, help_text='Days of the period elapsed through the computed date')),
                ('days_remaining', models.IntegerField(default=0, help_text='Days of the period left after the computed date')),
                ('seasonality_applied', models.BooleanField(default=False, help_text='Whether day-of-week factors were applied (false = pure linear)')),
                ('dow_factors', models.JSONField(blank=True, default=dict, help_text="Day-of-week spend factors keyed by weekday '0'-'6' (Monday=0)")),
                ('computed_for_date', models.DateField(help_text="The 'today' the forecast was computed for")),
                ('computed_at', models.DateTimeField(auto_now=True, help_text='When this forecast was last recomputed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(help_text='The campaign this forecast describes', on_delete=django.db.models.deletion.CASCADE, related_name='pacing_forecast', to='campaign.campaign')),
            ],
            options={
                'db_table': 'campaign_pacing_forecast',
                'indexes': [models.Index(fields=['status'], name='campaign_pa_status_f05de2_idx'), models.Index(fields=['computed_for_date'], name='campaign_pa_compute_aa4257_idx')],
            },
        ),
    ]
