# Generated by Django 4.2.23 on 2026-08-29 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_widen_password_rotation_clock_skew'),
        ('calendars', '0004_calendarevent_unique_cal_event_per_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL segment, unique within the organisation.', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('slot_increment_minutes', models.PositiveIntegerField(default=15)),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0)),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0)),
                ('min_notice_minutes', models.PositiveIntegerField(default=60)),
                ('max_advance_days', models.PositiveIntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', help_text="Owner's timezone; availability windows are wall-clock in this zone.", max_length=100)),
                ('availability_windows', models.JSONField(blank=True, default=list, help_text="Weekly windows as [{'weekday': 0-6 (Mon-Sun), 'start': 'HH:MM', 'end': 'HH:MM'}]. Empty falls back to the owner's CalendarSettings working hours.")),
                ('is_active', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(help_text='Calendar that bookings are written to.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='calendars.calendar')),
                ('organization', models.ForeignKey(help_text="Tenant boundary. Must match the owner's organization.", on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='core.organization')),
                ('owner', models.ForeignKey(help_text='The person whose time is being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['organization', 'slug'], name='calendars_b_organiz_a1b403_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bookinglink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'slug'), name='uniq_booking_link_org_slug'),
        ),
    ]
