# Generated by Django 4.2.23 on 2026-08-31 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_created_by(apps, schema_editor):
    """
    Every link that exists today was made by its own host, so attributing it to
    the owner keeps history accurate rather than leaving a null that reads as
    "creator unknown".
    """
    BookingLink = apps.get_model('calendars', 'BookingLink')
    BookingLink.objects.filter(created_by__isnull=True).update(
        created_by=models.F('owner')
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0005_bookinglink_bookinglink_uniq_booking_link_org_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglink',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="Who set the link up. Differs from owner when a colleague arranges time on the host's behalf. Null once that account is removed - the link belongs to the host, so it outlives its creator.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinglink',
            name='owner',
            field=models.ForeignKey(help_text='The host: the person whose time is being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_created_by, migrations.RunPython.noop),
    ]
