# Generated by Django 4.2.23 on 2026-09-01 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0006_bookinglink_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglink',
            name='invitee_email',
            field=models.EmailField(blank=True, default='', help_text='The intended guest when they have no account - address only.', max_length=254),
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='invitee_user',
            field=models.ForeignKey(blank=True, help_text='The intended guest, when they already have an account here. Gets notified in-app; a booking they make is tied back to them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_booking_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
