# Generated by Django 4.2.23 on 2026-09-01 08:56

from django.conf import settings
from django.db import migrations, models


def carry_invitees_over(apps, schema_editor):
    """
    Move the single invitee onto the plural fields before the old columns go.

    makemigrations put the removals first, which would have dropped whoever a
    link was already addressed to.
    """
    BookingLink = apps.get_model('calendars', 'BookingLink')
    for link in BookingLink.objects.all().iterator():
        if link.invitee_user_id:
            link.invitee_users.add(link.invitee_user_id)
        if link.invitee_email:
            link.invitee_emails = [link.invitee_email]
            link.save(update_fields=['invitee_emails'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0007_bookinglink_invitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglink',
            name='invitee_emails',
            field=models.JSONField(blank=True, default=list, help_text='Intended guests with no account, as a list of addresses. Kept separate from invitee_users so a guest who later registers is not silently promoted to an account they may not own.'),
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='invitee_users',
            field=models.ManyToManyField(blank=True, help_text='Intended guests who already have an account here. Each is notified in-app, and a booking they make is tied back to them.', related_name='invited_booking_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(carry_invitees_over, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='bookinglink',
            name='invitee_email',
        ),
        migrations.RemoveField(
            model_name='bookinglink',
            name='invitee_user',
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Optional contact number. Collected from guests booking through a public link, who have no profile to look one up from.', max_length=50),
        ),
    ]
