# Generated by Django 4.2.23 on 2026-07-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_importedcsvfile_spreadsheet'),
        ('agent', '0036_agentworkflowtemplate_slug'),
    ]

    operations = [
    ]
