# Generated by Django 4.2.30 on 2026-09-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_project_ai_analysis_enabled'),
        ('agent', '0037_merge_20260716_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='core.project'),
        ),
    ]
