# Generated by Django 4.2.23 on 2026-09-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_0023_sessions_and_ai'),
        ('spreadsheet', '0012_spreadsheetaiconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Function name as used in formulas, e.g. MYROAS', max_length=64)),
                ('params', models.JSONField(default=list, help_text="Ordered list of parameter names, e.g. ['revenue', 'cost']")),
                ('expression', models.TextField(help_text="Formula body using param names, e.g. 'revenue / cost'")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_defined_functions', to='core.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userdefinedfunction',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_deleted=False),
                fields=('project', 'name'),
                name='unique_active_udf_name_per_project',
            ),
        ),
    ]
