# Generated by Django 4.2.23 on 2026-09-20 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_merge_0023_sessions_and_ai'),
        ('report', '0003_alter_reporttask_audience_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, unique within the project', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='Optional explanation of what this KPI measures')),
                ('formula', models.TextField(help_text="Formula over metric names, e.g. 'revenue / spend'")),
                ('display_format', models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('percent', 'Percent')], default='number', help_text='How the computed value should be rendered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_kpis', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this KPI belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_kpis', to='core.project')),
            ],
            options={
                'db_table': 'report_custom_kpi',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customkpi',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_custom_kpi_name_per_project'),
        ),
    ]
