# Generated by Django 4.2.23 on 2026-09-27 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_0023_sessions_and_ai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_customkpi_customkpi_uniq_custom_kpi_name_per_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unguessable token placed in the public URL. Generated on save when blank.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When the link stops working. The public read path compares this to the server clock.')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the link was revoked. Null means it has not been revoked.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_share_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project whose Custom KPIs this link may show. This is the scope.', on_delete=django.db.models.deletion.CASCADE, related_name='report_share_links', to='core.project')),
            ],
            options={
                'db_table': 'report_share_link',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportsharelink',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('project',), name='uniq_active_report_share_link_per_project'),
        ),
    ]
