# Generated by Django 4.2.30 on 2026-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_documentindexstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentindexstate',
            name='dirty_since',
            field=models.DateTimeField(blank=True, help_text='Set when a source mutation has occurred that is not yet confirmed reconciled into DocumentChunk. NULL means the last successful reconcile (or confirmed exclusion) is believed current. Distinct from `status`: see class docstring.', null=True),
        ),
        migrations.AddIndex(
            model_name='documentindexstate',
            index=models.Index(condition=models.Q(('dirty_since__isnull', False)), fields=['dirty_since'], name='rag_index_state_dirty_since'),
        ),
    ]
