# Generated by Django 4.2.23 on 2026-08-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_widen_password_rotation_clock_skew'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_concurrent_sessions',
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
